### ISSUE TITLE
[meta-0.5] Update the API to match upstream

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#196]
Rough list:
- [x] https://github.com/gpuweb/gpuweb/pull/589 - rename view dimension
- [x] https://github.com/gpuweb/gpuweb/pull/590 - Bind Group entries
- [x] https://github.com/gpuweb/gpuweb/pull/595 - comparison sampler flag
- [x] https://github.com/gpuweb/gpuweb/pull/554 - vertex/index buffer size
- [x] https://github.com/gpuweb/gpuweb/pull/468 - single vertex buffer at a time
- [x] https://github.com/gpuweb/gpuweb/pull/532 - write-only texture storage
- [x] https://github.com/gpuweb/gpuweb/pull/517 - make `imageHeight` optional
- [x] https://github.com/gpuweb/gpuweb/pull/490 - naming for the queue accessor
- [x] https://github.com/gpuweb/gpuweb/pull/383 - remove snorm formats
- [x] https://github.com/gpuweb/gpuweb/pull/357 - remove other formats
- [x] https://github.com/gpuweb/gpuweb/pull/358 - discard to zero
- [x] https://github.com/gpuweb/gpuweb/pull/347 - optional rasterizer
- [ ] https://github.com/gpuweb/gpuweb/pull/591 - support either a WGSL string or a SPIR-V u32 slice (no need to support WGSL yet, panic is fine)

**Comment by kaimast** [comment]
Are the checkmarks up to date? Seems like all the referenced pull requests are merged.

**Comment by kvark** [comment]
Thank you for the heads up! This can be considered closed now - addressed by #518, which we picked up recently.
